<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net6.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<PlatformTarget>x86</PlatformTarget>
		<Platforms>x86;AnyCPU</Platforms>
		<ApplicationIcon>idollogo.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AssemblyName>Pharmacy Demo</AssemblyName>
		<Version>2.1.2</Version>
		<Title>Pharmacy Demo - IDOL</Title>
		<Authors>IDOL Technologies</Authors>
		<Product>Pharmacy Self Check-out</Product>
		<Description>Pharmacy Self Check-out Demo fot Dr Sulaiman Al Habib Pharmacies</Description>
		<Copyright>2024</Copyright>
	</PropertyGroup>

  <!--<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>True</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>True</Optimize>
  </PropertyGroup>-->

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<Optimize>False</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
		<Optimize>False</Optimize>
	</PropertyGroup>
	

  <ItemGroup>
    <None Remove="leaflet1.jpg" />
  </ItemGroup>
	

  <ItemGroup>
    <Content Include="favicon.ico" />
    <Content Include="idollogo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.8.0.20230708" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.8.0.20230708" />
    <PackageReference Include="System.IO.Ports" Version="7.0.0" />
    <PackageReference Include="XamlAnimatedGif" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="POS.Devices.OPOSPOSPrinter">
      <HintPath>POS.Devices.OPOSPOSPrinter.dll</HintPath>
      <Private>True</Private>
      <Aliases></Aliases>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="leaflet1.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="ccllampdll.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="CCLLampDll452.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="CCLLampDll452.lib">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="haarcascade_frontalface_default.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="images\leaflet1.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="LoadWinRing.lib">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="POS.Devices.OPOSPOSPrinter.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="products\products.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="WinRing0.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="WinRing0.sys">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="WinRing0x64.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="WinRing0x64.sys">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Page Update="UserControls\ucItemScreen.xaml">
      <CopyToOutputDirectory></CopyToOutputDirectory>
      <Generator></Generator>
    </Page>
    <Page Update="UserControls\ucPaymentScreen.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

</Project>
